name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    container:
      image: osrf/ros:jazzy-desktop
    strategy:
      matrix:
        os: [ubuntu-24.04]
      fail-fast: false
    steps:

      - name: build and test
        uses: ros-tooling/action-ros-ci@0.4.1
        with:
          package-name: computer_vision
          target-ros2-distro: rolling
          vcs-repo-file-url: ""
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }