name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ROS2:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup ROS 2 environment
        uses: ros-tooling/setup-ros@0.7.10
        with:
          ros-distro: jazzy

      - name: Build ROS 2 package
        uses: ros-tooling/action-ros-ci@0.4.1
        with:
          package-name: abr_ffmpeg_image_transport
          target-ros2-distro: jazzy
